name: merge_stage_test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_zh-CN.md'
      - 'docs/**'
<<<<<<< HEAD
      - '.owners.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.dev_scripts/**'
      - '.circleci/**'
      - 'configs/**'
      - 'projects/**'

    branches:
      - dev-1.x
      - test-1.x
      - main
      - test-branch
=======
      - 'demo/**'
      - '.dev_scripts/**'
      - '.circleci/**'
    branches:
      - master
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_cpu_py:
<<<<<<< HEAD
    runs-on: ubuntu-22.04
=======
    runs-on: ubuntu-18.04
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        torch: [1.8.1]
        include:
          - torch: 1.8.1
            torchvision: 0.9.1
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade && pip install wheel
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: Install MMEngine
        run: pip install git+https://github.com/open-mmlab/mmengine.git@main
      - name: Install MMCV
        run: |
          pip install -U openmim
          mim install 'mmcv >= 2.0.0'
      - name: Install other dependencies
        run: |
          pip install -r requirements/tests.txt
=======
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get MMCV_TORCH as the environment variable
        run: . .github/workflows/scripts/get_mmcv_var.sh ${{matrix.torch}}
        shell: bash
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install MMCV
        run: pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch${MMCV_TORCH}/index.html
      - name: Install other dependencies
        run: pip install -r requirements.txt
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
      - name: Build and install
        run: rm -rf .eggs && pip install -e .
      - name: Run unittests and generate coverage report
        run: |
<<<<<<< HEAD
          coverage run --branch --source mmagic -m pytest tests/
          coverage xml
          coverage report -m

  build_cpu_pt:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7]
        torch: [1.8.1, 1.9.1, 1.10.1, 1.11.0, 1.12.1, 1.13.0]
        include:
=======
          coverage run --branch --source mmedit -m pytest tests/
          coverage xml
          coverage report -m
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build_cpu_pt:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
        torch: [1.5.1, 1.6.0, 1.7.1, 1.8.1, 1.9.1, 1.10.1, 1.11.0]
        include:
          - torch: 1.5.1
            torchvision: 0.6.1
          - torch: 1.6.0
            torchvision: 0.7.0
          - torch: 1.7.1
            torchvision: 0.8.2
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
          - torch: 1.8.1
            torchvision: 0.9.1
          - torch: 1.9.1
            torchvision: 0.10.1
          - torch: 1.10.1
            torchvision: 0.11.2
          - torch: 1.11.0
            torchvision: 0.12.0
<<<<<<< HEAD
          - torch: 1.12.1
            torchvision: 0.13.1
          - torch: 1.13.0
            torchvision: 0.14.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade && pip install wheel
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: Install MMEngine
        run: pip install git+https://github.com/open-mmlab/mmengine.git@main
      - name: Install MMCV
        run: |
          pip install -U openmim
          mim install 'mmcv >= 2.0.0'
      - name: Install other dependencies
        run: |
          pip install -r requirements/tests.txt
=======
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install MMCV
        run: pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch${MMCV_TORCH}/index.html
      - name: Install other dependencies
        run: pip install -r requirements.txt
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
      - name: Build and install
        run: rm -rf .eggs && pip install -e .
      - name: Run unittests and generate coverage report
        run: |
<<<<<<< HEAD
          coverage run --branch --source mmagic -m pytest tests/
          coverage xml --omit="**/stylegan3_ops/*,**/conv2d_gradfix.py,**/grid_sample_gradfix.py,**/misc.py,**/upfirdn2d.py,**all_gather_layer.py"
=======
          coverage run --branch --source mmedit -m pytest tests/
          coverage xml
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
          coverage report -m
      # Only upload coverage report for python3.7 && pytorch1.8.1 cpu
      - name: Upload coverage to Codecov
        if: ${{matrix.torch == '1.8.1' && matrix.python-version == '3.7'}}
        uses: codecov/codecov-action@v1.0.14
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false

  build_cu102:
<<<<<<< HEAD
    runs-on: ubuntu-22.04
=======
    runs-on: ubuntu-18.04
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
    container:
      image: pytorch/pytorch:1.8.1-cuda10.2-cudnn7-devel
    strategy:
      matrix:
        python-version: [3.7]
        include:
          - torch: 1.8.1
            cuda: 10.2
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade && pip install wheel
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2204/x86_64/7fa2af80.pub
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
      - name: Install PyTorch
        run: pip install torch==1.8.1+cpu torchvision==0.9.1+cpu -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
      - name: Install mmagic dependencies
        run: |
          pip install -U openmim
          mim install 'mmcv >= 2.0.0'
          pip install -r requirements/tests.txt
      - name: Build and install
        run: |
          pip install -e .

  build_cu116:
    runs-on: ubuntu-22.04
    container:
      image: pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel
    strategy:
      matrix:
        python-version: [3.7]
        include:
          - torch: 1.8.1
            cuda: 10.2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade && pip install wheel
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2204/x86_64/7fa2af80.pub
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
      - name: Install PyTorch
        run: pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Install mmagic dependencies
        run: |
          pip install git+https://github.com/open-mmlab/mmengine.git@main
          pip install -U openmim
          mim install 'mmcv >= 2.0.0'
          pip install -r requirements/tests.txt
      - name: Build and install
        run: |
          pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --branch --source mmagic -m pytest tests/
          coverage xml --omit="**/stylegan3_ops/*,**/conv2d_gradfix.py,**/grid_sample_gradfix.py,**/misc.py,**/upfirdn2d.py,**all_gather_layer.py"
          coverage report -m

  build_windows:
    runs-on: windows-2022
    strategy:
      matrix:
        python: [3.7]
        platform: [cpu, cu111]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install pip --upgrade && pip install wheel
=======
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
      - name: Install Python-dev
        run: apt-get update && apt-get install -y python${{matrix.python-version}}-dev
        if: ${{matrix.python-version != 3.9}}
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
      - name: Install mmediting dependencies
        run: |
          pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch${MMCV_TORCH}/index.html
          pip install -r requirements.txt
      - name: Build and install
        run: |
          python setup.py check -m -s
          TORCH_CUDA_ARCH_LIST=7.0 pip install -e .
  build_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        python: [3.7]
        platform: [cpu, cu102]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install pip --upgrade
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
      - name: Install lmdb
        run: python -m pip install lmdb
      - name: Install PyTorch
        run: python -m pip install torch==1.8.1+${{matrix.platform}} torchvision==0.9.1+${{matrix.platform}} -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
<<<<<<< HEAD
      - name: Install mmagic dependencies
        run: |
          python -m pip install git+https://github.com/open-mmlab/mmengine.git@main
          python -m pip install -U openmim
          mim install 'mmcv >= 2.0.0'
          python -m pip install -r requirements/tests.txt
=======
      - name: Install mmediting dependencies
        run: |
          python -m pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8/index.html --only-binary mmcv-full
          python -m pip install -r requirements.txt
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
      - name: Build and install
        run: |
          python -m pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          pytest tests/
<<<<<<< HEAD
=======
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
>>>>>>> 6f2f3ae2ad3e365f94bbf19c01a1d1056dad3895
